import { TestBed } from '@angular/core/testing';
import {
  HttpClientTestingModule,
  HttpTestingController,
} from '@angular/common/http/testing';
import { ForecastService } from './forecast.service';

describe('ForecastService', () => {
  let httpTestingController: HttpTestingController;
  let service: ForecastService;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
    });
    httpTestingController = TestBed.get(HttpTestingController);
    service = TestBed.inject(ForecastService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });

  it('Foreast Data should use GET to retrieve data', () => {
    service.loadWeatherForecast('London').subscribe();

    const testRequest = httpTestingController.expectOne(
      'http://api.weatherapi.com/v1/forecast.json?key=6c26074ad39d454eb9f132032221512&q=London&days=10&aqi=no&alerts=no'
    );

    expect(testRequest.request.method).toEqual('GET');
  });

  it('Foreast Data should return No matching location found message when enters an unmatching location', (done) => {
    const expectedData = [
      {
        "error": {
            "code": 1006,
            "message": "No matching location found."
        }
    }
    ];
    service.loadWeatherForecast('Lowqer').subscribe((data) => {
      expect(data).toEqual(expectedData);
      done();
    });
    const testRequest = httpTestingController.expectOne(
      'http://api.weatherapi.com/v1/forecast.json?key=6c26074ad39d454eb9f132032221512&q=Lowqer&days=10&aqi=no&alerts=no'
    );

    testRequest.flush(expectedData);
  });

  it('Foreast Data should return expected data', (done) => {
    const expectedData = [
      {
        "location": {
            "name": "London",
            "region": "City of London, Greater London",
            "country": "United Kingdom",
            "lat": 51.52,
            "lon": -0.11,
            "tz_id": "Europe/London",
            "localtime_epoch": 1671349973,
            "localtime": "2022-12-18 7:52"
        },
        "current": {
            "last_updated_epoch": 1671349500,
            "last_updated": "2022-12-18 07:45",
            "temp_c": 1.0,
            "temp_f": 33.8,
            "is_day": 0,
            "condition": {
                "text": "Clear",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                "code": 1000
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 100,
            "wind_dir": "E",
            "pressure_mb": 1020.0,
            "pressure_in": 30.12,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 86,
            "cloud": 0,
            "feelslike_c": -2.8,
            "feelslike_f": 27.0,
            "vis_km": 8.0,
            "vis_miles": 4.0,
            "uv": 1.0,
            "gust_mph": 13.6,
            "gust_kph": 22.0
        },
        "forecast": {
            "forecastday": [
                {
                    "date": "2022-12-18",
                    "date_epoch": 1671321600,
                    "day": {
                        "maxtemp_c": 6.1,
                        "maxtemp_f": 43.0,
                        "mintemp_c": -0.7,
                        "mintemp_f": 30.7,
                        "avgtemp_c": 2.9,
                        "avgtemp_f": 37.2,
                        "maxwind_mph": 14.5,
                        "maxwind_kph": 23.4,
                        "totalprecip_mm": 5.2,
                        "totalprecip_in": 0.2,
                        "totalsnow_cm": 0.0,
                        "avgvis_km": 8.6,
                        "avgvis_miles": 5.0,
                        "avghumidity": 84.0,
                        "daily_will_it_rain": 1,
                        "daily_chance_of_rain": 93,
                        "daily_will_it_snow": 0,
                        "daily_chance_of_snow": 0,
                        "condition": {
                            "text": "Moderate rain",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
                            "code": 1189
                        },
                        "uv": 1.0
                    },
                    "astro": {
                        "sunrise": "08:02 AM",
                        "sunset": "03:52 PM",
                        "moonrise": "01:37 AM",
                        "moonset": "01:00 PM",
                        "moon_phase": "Waning Crescent",
                        "moon_illumination": "26"
                    },
                    "hour": [
                        {
                            "time_epoch": 1671321600,
                            "time": "2022-12-18 00:00",
                            "temp_c": -0.7,
                            "temp_f": 30.7,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 5.4,
                            "wind_kph": 8.6,
                            "wind_degree": 143,
                            "wind_dir": "SE",
                            "pressure_mb": 1023.0,
                            "pressure_in": 30.21,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 82,
                            "cloud": 7,
                            "feelslike_c": -3.8,
                            "feelslike_f": 25.2,
                            "windchill_c": -3.8,
                            "windchill_f": 25.2,
                            "heatindex_c": -0.7,
                            "heatindex_f": 30.7,
                            "dewpoint_c": -3.4,
                            "dewpoint_f": 25.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.2,
                            "gust_kph": 18.0,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671325200,
                            "time": "2022-12-18 01:00",
                            "temp_c": -0.5,
                            "temp_f": 31.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 5.4,
                            "wind_kph": 8.6,
                            "wind_degree": 142,
                            "wind_dir": "SE",
                            "pressure_mb": 1023.0,
                            "pressure_in": 30.2,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 80,
                            "cloud": 33,
                            "feelslike_c": -3.5,
                            "feelslike_f": 25.7,
                            "windchill_c": -3.5,
                            "windchill_f": 25.7,
                            "heatindex_c": -0.5,
                            "heatindex_f": 31.1,
                            "dewpoint_c": -3.5,
                            "dewpoint_f": 25.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.2,
                            "gust_kph": 18.0,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671328800,
                            "time": "2022-12-18 02:00",
                            "temp_c": -0.6,
                            "temp_f": 30.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 4.9,
                            "wind_kph": 7.9,
                            "wind_degree": 132,
                            "wind_dir": "SE",
                            "pressure_mb": 1023.0,
                            "pressure_in": 30.2,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 80,
                            "cloud": 17,
                            "feelslike_c": -3.4,
                            "feelslike_f": 25.9,
                            "windchill_c": -3.4,
                            "windchill_f": 25.9,
                            "heatindex_c": -0.6,
                            "heatindex_f": 30.9,
                            "dewpoint_c": -3.5,
                            "dewpoint_f": 25.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 10.3,
                            "gust_kph": 16.6,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671332400,
                            "time": "2022-12-18 03:00",
                            "temp_c": -0.4,
                            "temp_f": 31.3,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 5.8,
                            "wind_kph": 9.4,
                            "wind_degree": 134,
                            "wind_dir": "SE",
                            "pressure_mb": 1022.0,
                            "pressure_in": 30.18,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 79,
                            "cloud": 32,
                            "feelslike_c": -3.6,
                            "feelslike_f": 25.5,
                            "windchill_c": -3.6,
                            "windchill_f": 25.5,
                            "heatindex_c": -0.4,
                            "heatindex_f": 31.3,
                            "dewpoint_c": -3.6,
                            "dewpoint_f": 25.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.6,
                            "gust_kph": 18.7,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671336000,
                            "time": "2022-12-18 04:00",
                            "temp_c": 0.1,
                            "temp_f": 32.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.9,
                            "wind_kph": 11.2,
                            "wind_degree": 141,
                            "wind_dir": "SE",
                            "pressure_mb": 1021.0,
                            "pressure_in": 30.16,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 75,
                            "cloud": 11,
                            "feelslike_c": -3.5,
                            "feelslike_f": 25.7,
                            "windchill_c": -3.5,
                            "windchill_f": 25.7,
                            "heatindex_c": 0.1,
                            "heatindex_f": 32.2,
                            "dewpoint_c": -3.8,
                            "dewpoint_f": 25.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 12.8,
                            "gust_kph": 20.5,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671339600,
                            "time": "2022-12-18 05:00",
                            "temp_c": -0.1,
                            "temp_f": 31.8,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.9,
                            "wind_kph": 11.2,
                            "wind_degree": 133,
                            "wind_dir": "SE",
                            "pressure_mb": 1021.0,
                            "pressure_in": 30.15,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 75,
                            "cloud": 25,
                            "feelslike_c": -3.7,
                            "feelslike_f": 25.3,
                            "windchill_c": -3.7,
                            "windchill_f": 25.3,
                            "heatindex_c": -0.1,
                            "heatindex_f": 31.8,
                            "dewpoint_c": -4.0,
                            "dewpoint_f": 24.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 12.8,
                            "gust_kph": 20.5,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671343200,
                            "time": "2022-12-18 06:00",
                            "temp_c": 0.4,
                            "temp_f": 32.7,
                            "is_day": 0,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                "code": 1009
                            },
                            "wind_mph": 7.8,
                            "wind_kph": 12.6,
                            "wind_degree": 136,
                            "wind_dir": "SE",
                            "pressure_mb": 1020.0,
                            "pressure_in": 30.13,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 73,
                            "cloud": 100,
                            "feelslike_c": -3.5,
                            "feelslike_f": 25.7,
                            "windchill_c": -3.5,
                            "windchill_f": 25.7,
                            "heatindex_c": 0.4,
                            "heatindex_f": 32.7,
                            "dewpoint_c": -3.8,
                            "dewpoint_f": 25.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.6,
                            "gust_kph": 22.0,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671346800,
                            "time": "2022-12-18 07:00",
                            "temp_c": 0.8,
                            "temp_f": 33.4,
                            "is_day": 0,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                "code": 1009
                            },
                            "wind_mph": 8.1,
                            "wind_kph": 13.0,
                            "wind_degree": 136,
                            "wind_dir": "SE",
                            "pressure_mb": 1020.0,
                            "pressure_in": 30.12,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 72,
                            "cloud": 100,
                            "feelslike_c": -3.0,
                            "feelslike_f": 26.6,
                            "windchill_c": -3.0,
                            "windchill_f": 26.6,
                            "heatindex_c": 0.8,
                            "heatindex_f": 33.4,
                            "dewpoint_c": -3.6,
                            "dewpoint_f": 25.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.6,
                            "gust_kph": 22.0,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671350400,
                            "time": "2022-12-18 08:00",
                            "temp_c": 1.2,
                            "temp_f": 34.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 8.1,
                            "wind_kph": 13.0,
                            "wind_degree": 143,
                            "wind_dir": "SE",
                            "pressure_mb": 1020.0,
                            "pressure_in": 30.11,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 72,
                            "cloud": 49,
                            "feelslike_c": -2.5,
                            "feelslike_f": 27.5,
                            "windchill_c": -2.5,
                            "windchill_f": 27.5,
                            "heatindex_c": 1.2,
                            "heatindex_f": 34.2,
                            "dewpoint_c": -3.3,
                            "dewpoint_f": 26.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.6,
                            "gust_kph": 22.0,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671354000,
                            "time": "2022-12-18 09:00",
                            "temp_c": 1.5,
                            "temp_f": 34.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                                "code": 1006
                            },
                            "wind_mph": 9.4,
                            "wind_kph": 15.1,
                            "wind_degree": 142,
                            "wind_dir": "SE",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.09,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 71,
                            "cloud": 87,
                            "feelslike_c": -2.6,
                            "feelslike_f": 27.3,
                            "windchill_c": -2.6,
                            "windchill_f": 27.3,
                            "heatindex_c": 1.5,
                            "heatindex_f": 34.7,
                            "dewpoint_c": -3.1,
                            "dewpoint_f": 26.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 15.7,
                            "gust_kph": 25.2,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671357600,
                            "time": "2022-12-18 10:00",
                            "temp_c": 2.1,
                            "temp_f": 35.8,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 10.3,
                            "wind_kph": 16.6,
                            "wind_degree": 154,
                            "wind_dir": "SSE",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.06,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 69,
                            "cloud": 98,
                            "feelslike_c": -2.1,
                            "feelslike_f": 28.2,
                            "windchill_c": -2.1,
                            "windchill_f": 28.2,
                            "heatindex_c": 2.1,
                            "heatindex_f": 35.8,
                            "dewpoint_c": -2.9,
                            "dewpoint_f": 26.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 16.6,
                            "gust_kph": 26.6,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671361200,
                            "time": "2022-12-18 11:00",
                            "temp_c": 2.2,
                            "temp_f": 36.0,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 9.6,
                            "wind_kph": 15.5,
                            "wind_degree": 147,
                            "wind_dir": "SSE",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.05,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 72,
                            "cloud": 100,
                            "feelslike_c": -1.8,
                            "feelslike_f": 28.8,
                            "windchill_c": -1.8,
                            "windchill_f": 28.8,
                            "heatindex_c": 2.2,
                            "heatindex_f": 36.0,
                            "dewpoint_c": -2.3,
                            "dewpoint_f": 27.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 15.4,
                            "gust_kph": 24.8,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671364800,
                            "time": "2022-12-18 12:00",
                            "temp_c": 2.4,
                            "temp_f": 36.3,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 9.4,
                            "wind_kph": 15.1,
                            "wind_degree": 152,
                            "wind_dir": "SSE",
                            "pressure_mb": 1017.0,
                            "pressure_in": 30.02,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 76,
                            "cloud": 100,
                            "feelslike_c": -1.5,
                            "feelslike_f": 29.3,
                            "windchill_c": -1.5,
                            "windchill_f": 29.3,
                            "heatindex_c": 2.4,
                            "heatindex_f": 36.3,
                            "dewpoint_c": -1.4,
                            "dewpoint_f": 29.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 14.8,
                            "gust_kph": 23.8,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671368400,
                            "time": "2022-12-18 13:00",
                            "temp_c": 2.3,
                            "temp_f": 36.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Light drizzle",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                                "code": 1153
                            },
                            "wind_mph": 9.8,
                            "wind_kph": 15.8,
                            "wind_degree": 147,
                            "wind_dir": "SSE",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.98,
                            "precip_mm": 0.3,
                            "precip_in": 0.01,
                            "humidity": 82,
                            "cloud": 100,
                            "feelslike_c": -1.7,
                            "feelslike_f": 28.9,
                            "windchill_c": -1.7,
                            "windchill_f": 28.9,
                            "heatindex_c": 2.3,
                            "heatindex_f": 36.1,
                            "dewpoint_c": -0.4,
                            "dewpoint_f": 31.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 63,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 15.7,
                            "gust_kph": 25.2,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671372000,
                            "time": "2022-12-18 14:00",
                            "temp_c": 2.4,
                            "temp_f": 36.3,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 11.0,
                            "wind_kph": 17.6,
                            "wind_degree": 147,
                            "wind_dir": "SSE",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.95,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 89,
                            "cloud": 100,
                            "feelslike_c": -1.9,
                            "feelslike_f": 28.6,
                            "windchill_c": -1.9,
                            "windchill_f": 28.6,
                            "heatindex_c": 2.4,
                            "heatindex_f": 36.3,
                            "dewpoint_c": 0.8,
                            "dewpoint_f": 33.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 17.7,
                            "gust_kph": 28.4,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671375600,
                            "time": "2022-12-18 15:00",
                            "temp_c": 2.9,
                            "temp_f": 37.2,
                            "is_day": 1,
                            "condition": {
                                "text": "Light rain",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                                "code": 1183
                            },
                            "wind_mph": 11.0,
                            "wind_kph": 17.6,
                            "wind_degree": 155,
                            "wind_dir": "SSE",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.95,
                            "precip_mm": 1.2,
                            "precip_in": 0.05,
                            "humidity": 94,
                            "cloud": 100,
                            "feelslike_c": -1.2,
                            "feelslike_f": 29.8,
                            "windchill_c": -1.2,
                            "windchill_f": 29.8,
                            "heatindex_c": 2.9,
                            "heatindex_f": 37.2,
                            "dewpoint_c": 2.1,
                            "dewpoint_f": 35.8,
                            "will_it_rain": 1,
                            "chance_of_rain": 93,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 9.0,
                            "vis_miles": 5.0,
                            "gust_mph": 17.9,
                            "gust_kph": 28.8,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671379200,
                            "time": "2022-12-18 16:00",
                            "temp_c": 3.6,
                            "temp_f": 38.5,
                            "is_day": 0,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                "code": 1009
                            },
                            "wind_mph": 11.6,
                            "wind_kph": 18.7,
                            "wind_degree": 153,
                            "wind_dir": "SSE",
                            "pressure_mb": 1013.0,
                            "pressure_in": 29.93,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 97,
                            "cloud": 100,
                            "feelslike_c": -0.5,
                            "feelslike_f": 31.1,
                            "windchill_c": -0.5,
                            "windchill_f": 31.1,
                            "heatindex_c": 3.6,
                            "heatindex_f": 38.5,
                            "dewpoint_c": 3.1,
                            "dewpoint_f": 37.6,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 19.7,
                            "gust_kph": 31.7,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671382800,
                            "time": "2022-12-18 17:00",
                            "temp_c": 4.5,
                            "temp_f": 40.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Light drizzle",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                                "code": 1153
                            },
                            "wind_mph": 12.3,
                            "wind_kph": 19.8,
                            "wind_degree": 158,
                            "wind_dir": "SSE",
                            "pressure_mb": 1013.0,
                            "pressure_in": 29.9,
                            "precip_mm": 0.5,
                            "precip_in": 0.02,
                            "humidity": 97,
                            "cloud": 100,
                            "feelslike_c": 0.5,
                            "feelslike_f": 32.9,
                            "windchill_c": 0.5,
                            "windchill_f": 32.9,
                            "heatindex_c": 4.5,
                            "heatindex_f": 40.1,
                            "dewpoint_c": 4.1,
                            "dewpoint_f": 39.4,
                            "will_it_rain": 1,
                            "chance_of_rain": 92,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 21.5,
                            "gust_kph": 34.6,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671386400,
                            "time": "2022-12-18 18:00",
                            "temp_c": 6.1,
                            "temp_f": 43.0,
                            "is_day": 0,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                "code": 1009
                            },
                            "wind_mph": 13.2,
                            "wind_kph": 21.2,
                            "wind_degree": 163,
                            "wind_dir": "SSE",
                            "pressure_mb": 1012.0,
                            "pressure_in": 29.88,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 97,
                            "cloud": 100,
                            "feelslike_c": 2.3,
                            "feelslike_f": 36.1,
                            "windchill_c": 2.3,
                            "windchill_f": 36.1,
                            "heatindex_c": 6.1,
                            "heatindex_f": 43.0,
                            "dewpoint_c": 5.6,
                            "dewpoint_f": 42.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 20.6,
                            "gust_kph": 33.1,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671390000,
                            "time": "2022-12-18 19:00",
                            "temp_c": 6.8,
                            "temp_f": 44.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Light drizzle",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                                "code": 1153
                            },
                            "wind_mph": 13.6,
                            "wind_kph": 22.0,
                            "wind_degree": 167,
                            "wind_dir": "SSE",
                            "pressure_mb": 1011.0,
                            "pressure_in": 29.86,
                            "precip_mm": 0.3,
                            "precip_in": 0.01,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": 3.1,
                            "feelslike_f": 37.6,
                            "windchill_c": 3.1,
                            "windchill_f": 37.6,
                            "heatindex_c": 6.8,
                            "heatindex_f": 44.2,
                            "dewpoint_c": 6.3,
                            "dewpoint_f": 43.3,
                            "will_it_rain": 1,
                            "chance_of_rain": 91,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 20.6,
                            "gust_kph": 33.1,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671393600,
                            "time": "2022-12-18 20:00",
                            "temp_c": 7.0,
                            "temp_f": 44.6,
                            "is_day": 0,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                "code": 1009
                            },
                            "wind_mph": 13.9,
                            "wind_kph": 22.3,
                            "wind_degree": 172,
                            "wind_dir": "S",
                            "pressure_mb": 1011.0,
                            "pressure_in": 29.85,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": 3.3,
                            "feelslike_f": 37.9,
                            "windchill_c": 3.3,
                            "windchill_f": 37.9,
                            "heatindex_c": 7.0,
                            "heatindex_f": 44.6,
                            "dewpoint_c": 6.3,
                            "dewpoint_f": 43.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 22.8,
                            "gust_kph": 36.7,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671397200,
                            "time": "2022-12-18 21:00",
                            "temp_c": 7.7,
                            "temp_f": 45.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Light rain",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                                "code": 1183
                            },
                            "wind_mph": 14.1,
                            "wind_kph": 22.7,
                            "wind_degree": 174,
                            "wind_dir": "S",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.83,
                            "precip_mm": 2.1,
                            "precip_in": 0.08,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": 4.2,
                            "feelslike_f": 39.6,
                            "windchill_c": 4.2,
                            "windchill_f": 39.6,
                            "heatindex_c": 7.7,
                            "heatindex_f": 45.9,
                            "dewpoint_c": 7.0,
                            "dewpoint_f": 44.6,
                            "will_it_rain": 1,
                            "chance_of_rain": 91,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 9.0,
                            "vis_miles": 5.0,
                            "gust_mph": 22.8,
                            "gust_kph": 36.7,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671400800,
                            "time": "2022-12-18 22:00",
                            "temp_c": 8.4,
                            "temp_f": 47.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain possible",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 14.5,
                            "wind_kph": 23.4,
                            "wind_degree": 176,
                            "wind_dir": "S",
                            "pressure_mb": 1009.0,
                            "pressure_in": 29.8,
                            "precip_mm": 0.1,
                            "precip_in": 0.0,
                            "humidity": 95,
                            "cloud": 100,
                            "feelslike_c": 5.0,
                            "feelslike_f": 41.0,
                            "windchill_c": 5.0,
                            "windchill_f": 41.0,
                            "heatindex_c": 8.4,
                            "heatindex_f": 47.1,
                            "dewpoint_c": 7.6,
                            "dewpoint_f": 45.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 63,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 23.0,
                            "gust_kph": 37.1,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1671404400,
                            "time": "2022-12-18 23:00",
                            "temp_c": 9.0,
                            "temp_f": 48.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Light drizzle",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                                "code": 1153
                            },
                            "wind_mph": 14.3,
                            "wind_kph": 23.0,
                            "wind_degree": 185,
                            "wind_dir": "S",
                            "pressure_mb": 1009.0,
                            "pressure_in": 29.79,
                            "precip_mm": 0.7,
                            "precip_in": 0.03,
                            "humidity": 95,
                            "cloud": 100,
                            "feelslike_c": 5.8,
                            "feelslike_f": 42.4,
                            "windchill_c": 5.8,
                            "windchill_f": 42.4,
                            "heatindex_c": 9.0,
                            "heatindex_f": 48.2,
                            "dewpoint_c": 8.2,
                            "dewpoint_f": 46.8,
                            "will_it_rain": 1,
                            "chance_of_rain": 90,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 22.8,
                            "gust_kph": 36.7,
                            "uv": 1.0
                        }
                    ]
                }
            ]
        }
    }
    ];
 
    service.loadWeatherForecast("London").subscribe(data => {
      expect(data).toEqual(expectedData);
      done();
    });
 
    const testRequest = httpTestingController.expectOne(
      'http://api.weatherapi.com/v1/forecast.json?key=6c26074ad39d454eb9f132032221512&q=London&days=10&aqi=no&alerts=no'
    );
 
    testRequest.flush(expectedData);
  });
});
